---

ansible_user: ansible
ansible_become: true
ansible_become_method: sudo
ansible_ssh_user: user
ansible_ssh_pass: 12345
ansible_ssh_common_args:
  -o "StrictHostKeyChecking no"
  -o "UserKnownHostsFile /dev/null"
  -o "PreferredAuthentications password"
  -o "ControlPersist 60s"
  -o "ControlMaster auto"
ansible_ssh_pipelining: true
ansible_python_interpreter: auto_silent
display_skipped_hosts: false
