all:
  hosts:
    user-laptop:
    user-desktop:
  children:
    laptop:
      hosts:
        user-laptop:
          ansible_host: 10.0.0.10
    desktop:
      hosts:
        user-desktop:
          ansible_host: 10.0.0.20
